RockProgressif/RockProgressif/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RockProgressif.Data;
using RockProgressif.Models;
using RockProgressif.ViewModels;

namespace RockProgressif.Controllers
{
    public class AlbumsController : Controller
    {
        private readonly ProgRockBDContext _context;

        public AlbumsController(ProgRockBDContext context)
        {
            _context = context;
        }

        // GET: Albums
        public async Task<IActionResult> Index()
        {
            var progRockBDContext = _context.Albums.Include(a => a.Groupe);
            return View(await progRockBDContext.ToListAsync());
        }

        // GET: Albums/Create
        public IActionResult Create()
        {
            ViewData["GroupeId"] = new SelectList(_context.Groupes, "GroupeId", "Nom");
            return View();
        }

        // POST: Albums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AlbumCreationViewModel acvm)
        {
            if (ModelState.IsValid && acvm.FormFile.Length >= 0)
            {
                Album album = new Album
                {
                    GroupeId = acvm.GroupeId,
                    AlbumId = 0,
                    Nom = acvm.Nom,
                    DatePublication = acvm.DatePublication,
                    NoteCritiques = acvm.NoteCritiques,
                    NombreVentes = acvm.NombreVentes
                };

                MemoryStream stream = new MemoryStream();
                await acvm.FormFile.CopyToAsync(stream);
                byte[] fichier = stream.ToArray();
                album.CoverContent = fichier;

                await _context.Albums.AddAsync(album);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            ViewData["GroupeId"] = new SelectList(_context.Groupes, "GroupeId", "Nom", acvm.GroupeId);
            return View(acvm);
        }

        public async Task<IActionResult> Filtre()
        {
            AlbumsFiltreViewModel data = new AlbumsFiltreViewModel();

            data.albums = await _context.Albums.ToListAsync();
            ViewData["Groupes"] = new SelectList(_context.Groupes, "GroupeId", "Nom");

            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> Filtre(AlbumsFiltreViewModel afvm)
        {
            ViewData["Groupes"] = new SelectList(_context.Groupes, "GroupeId", "Nom");

            var albums = _context.Albums.AsQueryable();
            if (afvm.GroupeId > 0)
            {
                albums = albums.Where(a => a.GroupeId == afvm.GroupeId).AsQueryable();
            }
            if (afvm.NbVenteMin != null)
            {
                albums = albums.Where(a => a.NombreVentes >= afvm.NbVenteMin).AsQueryable();
            }
            if (afvm.NoteCritiqueMin != null)
            {
                albums = albums.Where(a => a.NoteCritiques >= afvm.NoteCritiqueMin).AsQueryable();
            }
    
            afvm.albums = await albums.ToListAsync();
            return View(afvm);
        }
    }
}

RockProgressif/RockProgressif/Controllers/ArtistesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RockProgressif.Data;
using RockProgressif.Models;

namespace RockProgressif.Controllers;

public class ArtistesController : Controller
{
    private readonly ProgRockBDContext _context;

    public ArtistesController(ProgRockBDContext context)
    {
        _context = context;
    }
        
    public async Task<IActionResult> LiensArtisteGroupes()
    {
        return _context.VwLiensArtisteGroupes != null ? 
            View(await _context.VwLiensArtisteGroupes.ToListAsync()) :
            Problem("Entity set 'ProgRockBDContext.Artistes'  is null.");
    }
}

RockProgressif/RockProgressif/Controllers/ChansonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using RockProgressif.Data;
using RockProgressif.Models;
using RockProgressif.ViewModels;

namespace RockProgressif.Controllers
{
    public class ChansonsController : Controller
    {
        private readonly ProgRockBDContext _context;

        public ChansonsController(ProgRockBDContext context)
        {
            _context = context;
        }

        // GET: Chansons
        public async Task<IActionResult> Index()
        {
            ViewData["Albums"] = new SelectList(_context.Albums, "AlbumId", "Nom");
            ChansonIndexViewModel data = new ChansonIndexViewModel();
            data.Chansons = await _context.Chansons.ToListAsync();
            return _context.Chansons != null
                ? View(data)
                : Problem("Entity set 'ProgRockBDContext.Chansons'  is null.");
        }

        [HttpPost]
        public async Task<IActionResult> Index(int AlbumId)
        {
            ChansonIndexViewModel data = new ChansonIndexViewModel();
            if (AlbumId != 0)
            {
                string query = "EXEC Albums.USP_GetChansonsAlbum @AlbumId";
                List<SqlParameter> parameters = new List<SqlParameter>
                {
                    new SqlParameter { ParameterName = "@AlbumID", Value = AlbumId }
                };
                data.Chansons = await _context.Chansons.FromSqlRaw(query, parameters.ToArray()).ToListAsync();
            }
            else
            {
                data.Chansons = await _context.Chansons.ToListAsync();
            }

            ViewData["Albums"] = new SelectList(_context.Albums, "AlbumId", "Nom");
            return View(data);
        }
    }
}

RockProgressif/RockProgressif/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RockProgressif</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RockProgressif.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RockProgressif</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Artistes" asp-action="LiensArtisteGroupes">V1.2_Vue</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Groupes" asp-action="Index">V1.3_Chiffrement</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Chansons" asp-action="Index">V1.4_Procedure_Stockee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Albums" asp-action="Index">V1.5_Gestion_Images</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Albums" asp-action="Filtre">V1.6_Performance_Filtre</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - RockProgressif - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>